name: Workflow
on:
  push:
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 20
            
      - name: Checkout   
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install dependencies
        run: npm install
      
      - name: Build Project
        run: npm run build 
        
      - name: Run Tests
        run: npm test -- --coverage

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=gotelloc 
            -Dsonar.projectKey=gotelloc_Laboratorio-final
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**,**/*.test.ts,**/*.spec.ts,**/*.test.tsx,**/*.spec.tsx
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.tests=src
            -Dsonar.test.inclusions=src/**/*.test.ts,src/**/*.spec.ts,src/**/*.test.tsx,src/**/*.spec.tsx
        
      
            
            
            
