name: Workflow
on:
  push:
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 16.x
            cache: npm
            
      - name: Install dependencies
        run: npm install
            
      - name: Construir el proyecto
        run: npm run build
  
      - name: Ejecutar pruebas
        run: npm test -- --coverage

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=gotelloc 
            -Dsonar.projectKey=gotelloc_Laboratorio-final
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**,**/*.test.js,**/*.spec.js
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
        
      
            
            
            
