name: Workflow
on:
  push:
jobs:
  SAST:
    runs-on: ubuntu-latest
    steps:
    
      - name: Clonacion de codigo
        uses: actions/checkout@v4
        
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
            node-version: 16.x
            cache: npm
            
      - name: Install dependencies
        run: npm install
        
      - name: Install Node.js dependencies
        run: npm ci

      - name: Run Vitest
        run: npx vitest --coverage --exclude **/integration.test.ts    

      - name: SonarCloud scan
        uses: SonarSource/sonarcloud-github-action@v2.3.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=gotelloc 
            -Dsonar.projectKey=gotelloc_Laboratorio-final
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**
        
      
            
            
            
